# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://count.3point5.info" # the base hostname & protocol for your site, e.g. http://example.com
domain: 3point5.info

# Build settings
remote_theme: rohanchandra/type-theme
  
theme_settings:
  title: Let's Get a Protest Count!
  description: Protest counting
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  rss: false
  email_address: ERVancouver@proton.me
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: 
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup
  search: false # Enable the search feature
  
  header_text: 
  header_text_feature_image: 
  footer_text: 
  
  post_navigation: false
  
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock